services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MongoUsernameDB
      - MONGO_INITDB_ROOT_PASSWORD=MongoPasswordDB
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    networks:
      - union-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=MongoUsernameDB
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoPasswordDB
      - ME_CONFIG_BASICAUTH_USERNAME=PageUsername
      - ME_CONFIG_BASICAUTH_PASSWORD=PagePassword
    ports:
      - '8003:8081'
    networks:
      - union-network

networks:
  union-network:
    driver: bridge