services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=MongoUsernameDB
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoPasswordDB
      - ME_CONFIG_BASICAUTH_USERNAME=PageUsername
      - ME_CONFIG_BASICAUTH_PASSWORD=PagePassword
    ports:
      - '8003:8081'
    networks:
      - mongo_individual-network

networks:
  mongo_individual-network:
    external: true