services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - '8004:80'
    environment:
      - PMA_ARBITRARY=1

    #environment:
      #- PMA_HOST=192.168.1.100  # Replace this IP with the IP address of your MySQL server.
      #- PMA_PORT=3306           # Optional: The port of MySQL, by default it is 3306.
      #- PMA_ARBITRARY=0         # Disable the option to specify an arbitrary server.

networks:
  network:
    driver: bridge